---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik-ingress
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 37.0.0
  url: oci://ghcr.io/traefik/helm/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-ingress
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: traefik-ingress
  install:
    crds:
      skip: true
    remediation:
      retries: 3
  upgrade:
    crds:
      skip: true
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: traefik-ingress-helm-values