---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    defaultPodOptions:
      priorityClassName: system-node-critical
    configMaps:
      config:
        data:
          config.yaml: |-
            devices:
              - name: tun
                groups:
                  - count: 3
                    paths:
                      - path: /dev/net/tun
    controllers:
      generic-device-plugin:
        type: daemonset
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/squat/generic-device-plugin
              tag: 1467dde@sha256:45787848aac84d6b8b592904614339fa82d7c0e422f3287d7f9913896ff3a3f7
            args:
              - --log-level=info
              - --config=/config/config.yaml
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            securityContext:
              privileged: true
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        type: configMap
        identifier: config
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      dev:
        type: hostPath
        hostPath: /dev
        globalMounts:
          - readOnly: true
      sys:
        type: hostPath
        hostPath: /sys
        globalMounts:
          - readOnly: true
      var-lib-kubelet-device-plugins:
        type: hostPath
        hostPath: /var/lib/kubelet/device-plugins