---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: njalla-webhook
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: cert-manager-webhook-njalla
      version: v0.1.0
      sourceRef:
        kind: HelmRepository
        name: charts-plutode
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    email: ${SECRET_EMAIL}
    groupName: acme.${SECRET_DOMAIN}
    njalla:
      existingSecret: bw-secrets-cert