---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-sr-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  # So that I can edit the resulting secret
  target:

    template:

      # Use inline templates to construct your desired config file that contains your secret
      data:
        TS_EXTRA_ARGS: '{{ printf "--accept-routes --login-server=%s" .loginserver }}'
        TS_AUTHKEY: '{{ .authkey }}'
  data:
  - secretKey: authkey
    remoteRef:
      key: "b0070da2-30d4-4b62-b70d-b36300df123d"
  - secretKey: loginserver
    remoteRef:
      key: "50925687-3129-4b99-95a0-b36300de9537"