---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-sr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      tailscale-sr:
        serviceAccount:
          identifier: tailscale-sr
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: network/multus-lan-1
          securityContext:
            fsGroup: 568
        type: deployment
        replicas: 1
        containers:
          app:
            env:
              NO_AUTOUPDATE: true
              PORT: &tailnetPort 45387
              TS_DEBUG_MTU: 1420
              TS_HOSTNAME: "tailscale-galaxy"
              TS_KUBE_SECRET: "tailscale-state"
              TS_ROUTES: "192.168.31.0/24,10.21.0.0/16"
              TS_TAILSCALED_EXTRA_ARGS: --debug=0.0.0.0:9001
              TS_SNAT_SUBNET_ROUTES: false
              TS_USERSPACE: true
              TZ: "${SECRET_TZ}"
            envFrom:
              - secretRef:
                  name: tailscale-sr-secrets
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.86.5@sha256:9e2bfdd9e2ce724df53f976d06a4a9933aa730dc655ace42798f4c73735d1cac
            probes:
              liveness: &probes
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /debug/pprof/
                    port: &tailscalePort 9001
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              limits:
                cpu: 1
                memory: 420Mi
              requests:
                cpu: 50m
                memory: 250Mi
            securityContext:
              fsGroup: 568
              runAsGroup: 568
              runAsNonRoot: true
              runAsUser: 568
              sysctls:
                - name: net.ipv4.ip_forward
                  value: "1"
                - name: net.ipv6.conf.all.forwarding
                  value: "1"
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_BIND_SERVICE
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    rbac:
      roles:
        tailscale-sr:
          enabled: true
          type: Role
          rules:
            - apiGroups: [""] # "" indicates the core API group
              resources: ["secrets"]
              # Create can not be restricted to a resource name.
              verbs: ["create"]
            - apiGroups: [""] # "" indicates the core API group
              resourceNames: ["tailscale-state"]
              resources: ["secrets"]
              verbs: ["get", "update", "patch"]
            - apiGroups: [""] # "" indicates the core API group
              resources: ["events"]
              verbs: ["get", "create", "patch"]
      bindings:
        tailscale-sr:
          enabled: true
          type: RoleBinding
          subjects:
            - kind: ServiceAccount
              name: "tailscale-sr"
          roleRef:
            identifier: tailscale-sr

    serviceAccount:
      tailscale-sr:
        enabled: true

    persistence:
      tmpfs:
        advancedMounts:
          tailscale-sr:
            app:
              - path: /.cache
                subPath: cache
              - path: /tmp
                subPath: tmp
              - path: /var/run
                subPath: run
        enabled: true
        type: emptyDir
      state:
        existingClaim: tailscale-state
        advancedMounts:
          tailscale-sr:
            app:
              - path: /var/lib/tailscale