apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        annotations: 
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  data:
  - secretKey: SECRET_DOMAIN
    remoteRef:
      key: "d2119a19-9f9b-40b9-a56a-b3480098876f"
  - secretKey: SECRET_EMAIL
    remoteRef:
      key: "36d0a0fc-4e2e-44d6-bc03-b348009894a3"
  - secretKey: SECRET_TZ
    remoteRef:
      key: "386be2c2-ee08-443e-8359-b3480098af16"