apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-io-auth
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore

  # So that I can edit the resulting secret
  target:

    template:
      type: kubernetes.io/dockerconfigjson 

      metadata:
        annotations: 
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"

      # Use inline templates to construct your desired config file that contains your secret
      data:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"B0bby31","password":"{{ .githubToken }}","auth":"{{ printf "B0bby31:%s" .githubToken | b64enc }}"}}}'

  data:
  - secretKey: githubToken
    remoteRef:
      key: "f07b243c-3f17-4154-acdf-b3480098fe2f"