apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      data:
        RADARR__AUTH__APIKEY: '{{ .api | toString }}'
  data:
  - secretKey: api
    remoteRef:
      key: "b68641f5-70e2-432d-b693-b26d010af886"
  - secretKey: RADARR__POSTGRES__PASSWORD
    remoteRef:
      key: "2414638d-a830-48e3-bcd1-b34500ed78c4"