---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      radarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 5.27.5@sha256:af67ce80302e21f7228e2da671943c48b27a25faf27e19c4fcb7ad33c1c0e3c0 
            env:
              RADARR__APP__INSTANCENAME: Radarr
              RADARR__APP__THEME: dark
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__AUTH__APIKEY: "${RADARR_AUTH_API}"
              RADARR__POSTGRES__HOST: local-database-rw.database.svc.cluster.local
              RADARR__POSTGRES__PORT: 5432
              RADARR__POSTGRES__MAINDB: radarr-main
              RADARR__POSTGRES__LOGDB: radarr-log
              RADARR__POSTGRES__USER: generalApps
              RADARR__POSTGRES__PASSWORD: ${password}
              RADARR__LOG__ANALYTICSENABLED: false
              RADARR__LOG__LEVEL: info
              RADARR__SERVER__PORT: &port 80
              TZ: Europe/Berlin
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: radarr
        ports:
          http:
            port: *port
    ingress:
      app:
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: radarr-tls
            hosts:
              - radarr.${SECRET_DOMAIN}
    persistence:
      config:
        type: emptyDir
      media:
        type: nfs
        server: 192.168.31.21
        path: /mnt/MainPool/Media/Movies
        globalMounts:
          - path: /media
      downloads:
        type: nfs
        server: 192.168.31.21
        path: /mnt/MainPool/Downloads/Torrents
        globalMounts:
          - path: /downloads
      tmp:
        type: emptyDir