---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "public-pool"
spec:
  blocks:
  - start: "192.168.15.40"
    stop: "192.168.15.90"
  serviceSelector:
    matchLabels:
      network: public