---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vibe-job-lp
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: cluster-secrets
      namespace: flux-system 
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/galaxy-cluster/kubernetes/apps/default/vibe-job-lp/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - name: bw-secrets-default
        kind: Secret
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m