---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-secrets-default
  namespace: default
spec:
  organizationId: "be4b7269-6a49-4702-a578-b2090189dfe8"
  secretName: bw-secrets-default
  map:
    - bwSecretId: 79e8ddf9-0688-4252-a73b-b33800c09a79
      secretKeyName: SECRET_DOMAIN
  authToken:
    secretName: bw-auth-token
    secretKey: token