apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        annotations: 
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  data:
  - secretKey: SECRET_DOMAIN
    remoteRef:
      key: "79e8ddf9-0688-4252-a73b-b33800c09a79"
  - secretKey: SECRET_EMAIL
    remoteRef:
      key: "95f27c48-44d1-44d5-946a-b3390151c2a2"
  - secretKey: SECRET_TZ
    remoteRef:
      key: "aa273082-c322-4a9a-9b3f-b34500e87d13"