---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bw-secrets-cert.yaml
  - ./bw-secrets-default.yaml
  - ./github-auth-secret.yaml