apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      data:
        SONARR__AUTH__APIKEY: '{{ .api | toString }}'
  data:
  - secretKey: api
    remoteRef:
      key: "1f2af75e-55c4-48c6-8b0e-b26d011137da"
  - secretKey: SONARR__POSTGRES__PASSWORD
    remoteRef:
      key: "2414638d-a830-48e3-bcd1-b34500ed78c4"