crds:
  enabled: true
replicaCount: 1
dns01RecursiveNameservers: kubedns.kube-system.svc.cluster.local:53
dns01RecursiveNameserversOnly: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true