apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: password
    remoteRef:
      key: "606a1e58-9574-47fb-ba64-b35500b1b6b6"