apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-replication
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-replication
      version: 0.16.8
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: redis
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    redisReplication:
      name: "local-redis"
      clusterSize: 3
      image: quay.io/opstree/redis
      tag: v7.0.15
      redisSecret:
        secretName: "redis-secrets"
        secretKey: "password"


    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "openebs-hostpath"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi