---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app letsencrypt-issuer
  namespace: &namespace cert-manager
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: njalla-webhook
      namespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/galaxy-cluster/kubernetes/apps/cert-manager/letsencrypt-issuer/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m