apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: njalla-api-secret
spec:
  refreshInterval: 300s
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: TS_AUTHKEY
    remoteRef:
      key: "92dc73d3-fa98-4069-afe1-b34c0164418e"
  - secretKey: TS_LOGIN_SERVER
    remoteRef:
      key: "21ad72f1-770a-472d-923b-b34c01632378"