---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-sr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      tailscale-sr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: network/multus-lan-1
        type: deployment
        replicas: 1
        containers:
          app:
            env:
              NO_AUTOUPDATE: true
              PORT: &tailnetPort 45387
              TS_DEBUG_MTU: 1420
              TS_EXTRA_ARGS: --accept-routes --login-server=${TS_LOGIN_SERVER}
              TS_HOSTNAME: "tailscale-galaxy"
              TS_KUBE_SECRET: ""
              TS_ROUTES: "192.168.231.0/24,192.168.13.0/24"
              TS_STATE_DIR: &path /tmp
              TS_TAILSCALED_EXTRA_ARGS: --debug=0.0.0.0:9001
              TS_SNAT_SUBNET_ROUTES: false
              TS_USERSPACE: true
              TZ: "${SECRET_TZ}"
            envFrom:
              - secretRef:
                  name: tailscale-sr-secrets
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.86.5@sha256:9e2bfdd9e2ce724df53f976d06a4a9933aa730dc655ace42798f4c73735d1cac
            probes:
              liveness: &probes
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /debug/pprof/
                    port: &tailscalePort 9001
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              limits:
                cpu: 1
                memory: 420Mi
              requests:
                cpu: 50m
                memory: 250Mi
            securityContext:
              fsGroup: 568
              runAsGroup: 568
              runAsNonRoot: true
              runAsUser: 568
              sysctls:
                - name: net.ipv4.ip_forward
                  value: "1"
                - name: net.ipv6.conf.all.forwarding
                  value: "1"
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_BIND_SERVICE
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      tmpfs:
        advancedMounts:
          tailscale-sr:
            app:
              - path: /.cache
                subPath: cache
              - path: /tmp
                subPath: tmp
              - path: /var/run
                subPath: run
        enabled: true
        type: emptyDir