apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mqtt-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: HA_PASS
    remoteRef:
      key: "4fb77b70-e79f-4935-9492-b3460151e4b5"
  - secretKey: NUKI_PASS
    remoteRef:
      key: "4ece53c9-3399-49f8-b5fb-b3460151f78c"