---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  values:
    configMaps:
      config:
        data:
          mosquitto.conf: |
            allow_anonymous false
            password_file /mosquitto/config_includes/passes.txt
            autosave_interval 60
            connection_messages false
            listener 1883 0.0.0.0
            per_listener_settings false
            persistence true
            persistence_location /config
      pass:
        data:
          passes.txt: |
            ha:${HA_PASS}
            nuki:${NUKI_PASS}
    controllers:
      mosquitto:
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000

        # Hash the password file
        initContainers:
          init-pass:
            securityContext:
              runAsUser: 0
            enabled: true    
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.22
            command: ["/bin/sh", "-c", "mosquitto_passwd -U /passes.txt && cp /passes.txt /data/passes.txt"]

        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.22
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 10m
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}-cache"
      pass-file:
        type: emptyDir
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config_includes
            init-pass:
              - path: /data

      config-file:
        type: configMap
        identifier: config
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
      pass-temp:
        type: configMap
        identifier: pass
        defaultMode: 448
        advancedMounts:
          mosquitto:
            init-pass:
              - path: /passes.txt
                subPath: passes.txt
          
              
    service:
      mosquitto-lb:
        controller: mosquitto
        type: LoadBalancer
        labels:
          network: local
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "mqtt.de.plutode.com"
          lbipam.cilium.io/ips: "10.11.0.111"
        ports:
          mqtt:
            port: 1883

      mosquitto-cluster:
        controller: mosquitto
        type: ClusterIP
        ports:
          mqtt:
            port: 1883