---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lan-pool"
spec:
  blocks:
  - start: "192.168.231.30"
    stop: "192.168.231.50"
  serviceSelector:
    matchLabels:
      network: lan