---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "public-pool"
spec:
  blocks:
    - start: "192.168.13.20"
      stop: "192.168.13.50"
  serviceSelector:
    matchLabels:
      network: local