---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 0
  values:
    ingress:
      enabled: true
      matchOverride: 'Host(auth.${SECRET_DOMAIN}) || Host(a.${SECRET_DOMAIN})'
      tls:
        enabled: true
      traefikCRD:
        enabled: true
        tls:
          certResolver: 'letsencrypt-prod'
          domainsOverride:
            - main: 'auth.${SECRET_DOMAIN}'
              sans:
                - 'a.${SECRET_DOMAIN}'
    pod:
      kind: 'DaemonSet'          
      securityContext:
        container:
          runAsUser: 2000
          runAsGroup: 2000
          fsGroup: 2000
        pod:
          readOnlyRootFilesystem: false
          privileged: false
          allowPrivilegeEscalation: false
    persistence:
      enabled: false
    secret:
      existingSecret: 'authelia-secrets'
      additionalSecrets: {}
    configMap:
      telemetry:
        serviceMonitor:
          enabled: true 
      default_2fa_method: 'totp'     
      theme: 'auto'
      definitions:
        network:
          vpn:
            - 100.64.0.0/10
          lan:
            - 192.168.31.0/24
            - 192.168.231.0/24
            - 192.168.131.0/24
          known:
            - 10.21.0.0/16
          iot:
            - 192.168.10.0/24
            - 10.11.0.0/16
            - 192.168.13.0/24
      totp:
        issuer: 'Plutode Inc.'
      webauthn:
        enable_passkey_login: false
      duo_api:
        enabled: false
      authentication_backend:
        refresh_interval: '1m'
        ldap:
          enabled: true
          implementation: 'lldap'
          address: 'ldaps://lldap-app.auth.svc.cluster.local:6360'
          base_dn: 'DC=plutode,DC=com'
          user: 'UID=authelia,OU=people,DC=plutode,DC=com'
          tls:
            server_name: 'lldap.${SECRET_DOMAIN}'
        file:
          enabled: false
      password_policy:
        standard:
          enabled: false
        zxcvbn:
          enabled: false
      access_control:
        default_policy: 'one_factor'
      session:
        cookies:
          - domain: 'plutode.com'
            authelia_url: 'auth.plutode.com'
            default_redirection_url: 'plutode.com'
            name: 'authelia-session'
            same_site: 'lax'
            inactivity: '5m'
            expiration: '1h'    
            remember_me: '1d'
        redis:
          enabled: true
          host: 'local-redis-master.redis.svc.cluster.local'
          port: 6379
      storage:
        postgres:
          enabled: true
          address: 'postgres://local-database-rw.database.svc.cluster.local'
          database: 'authelia'
          username: 'generalApps'
      notifier:
        smtp:
          enabled: true
          address: ''    
          sender: 'Plutode Inc. <support@plutode.com>'
          subject: '[Plutode Inc.] {title}'
          username: ''
      identity_providers:
        oidc:
          enabled: true
          claims_policies: {}
          jwks:
            - key:
                path: '/secrets/authelia-secrets/jwk.RS256.pem'
          clients: []
