---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authelia
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.46
  url: oci://ghcr.io/home-operations/charts-mirror/authelia
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: authelia
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 0
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      certManager: true
      rulesOverride:
        - host: "auth.${SECRET_DOMAIN}"
          path: "/"
        - host: "a.${SECRET_DOMAIN}"
          path: "/"
      tls:
        enabled: true
        secret: 'authelia-tls'
      traefikCRD:
        enabled: true
        disableIngressRoute: true
    pod:
      kind: 'DaemonSet'          
      securityContext:
        container:
          runAsUser: 2000
          runAsGroup: 2000
    persistence:
      enabled: false
    secret:
      existingSecret: 'authelia-secrets'
      additionalSecrets:
        authelia-oidc:
          items:
            - key: oidc_jwk_key
              path: jwk.RS256.pem
            - key: split_oidc_secret_digeset
              path: splitpro
    configMap:
      telemetry:
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true 
      default_2fa_method: 'totp'     
      theme: 'auto'
      definitions:
        network:
          vpn:
            - 100.64.0.0/10
          lan:
            - 192.168.31.0/24
            - 192.168.231.0/24
            - 192.168.131.0/24
          known:
            - 10.21.0.0/16
          iot:
            - 192.168.10.0/24
            - 10.11.0.0/16
            - 192.168.13.0/24
      totp:
        issuer: 'Plutode Inc.'
      webauthn:
        enable_passkey_login: false
      duo_api:
        enabled: false
      authentication_backend:
        refresh_interval: '1m'
        ldap:
          enabled: true
          implementation: 'lldap'
          address: 'ldaps://lldap-app.auth.svc.cluster.local:6360'
          base_dn: 'DC=plutode,DC=com'
          user: 'UID=authelia,OU=people,DC=plutode,DC=com'
          tls:
            server_name: 'lldap.${SECRET_DOMAIN}'
        file:
          enabled: false
      password_policy:
        standard:
          enabled: false
        zxcvbn:
          enabled: false
      access_control:
        default_policy: 'one_factor'
      session:
        cookies:
          - domain: plutode.com
            authelia_url: https://auth.${SECRET_DOMAIN}
            default_redirection_url: https://${SECRET_DOMAIN}
        redis:
          enabled: true
          host: 'local-redis-master.redis.svc.cluster.local'
          port: 6379
      storage:
        postgres:
          enabled: true
          address: 'tcp://local-database-rw.database.svc.cluster.local:5432'
          database: 'authelia'
          username: 'generalApps'
      notifier:
        smtp:
          enabled: true
          address: 'submission://smtp.protonmail.ch:587'    
          sender: 'Plutode Inc. <support@plutode.com>'
          subject: '[Plutode Inc.] {title}'
          username: 'support@plutode.com'
      identity_providers:
        oidc:
          enabled: true
          claims_policies: {}
          jwks:
            - key:
                path: '/secrets/authelia-oidc/jwk.RS256.pem'
          clients:
            - client_id: JvnneGoHZNFlJ3U2zRoOz8xhFYkTKAMNAfl-QH3C7YqZSstWPs44Hpr6RR0VrEr2LKqjxVkL
              client_name: SplitPro # Don't know
              client_secret:
                path: '/secrets/authelia-oidc/splitpro'
              public: false
              authorization_policy: one_factor # TODO: Change after correct 2nd factor setup done
              redirect_uris:
                - https://split.${SECRET_DOMAIN}/api/auth/callback/authelia
              scopes:
                - openid
                - profile
                - email
              userinfo_signed_response_alg: 'none'
