---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore

  data:
  - secretKey: oidc_jwk_key
    remoteRef:
      key: "a9f55885-674f-4d3f-894f-b35901614596"