---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app local-database
  namespace: &namespace database
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/galaxy-cluster/kubernetes/apps/database/local-database/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m