apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore

  # So that I can edit the resulting secret
  target:

    template:

      # Use inline templates to construct your desired config file that contains your secret
      data:
        LLDAP_DATABASE_URL: '{{ printf "postgresql://generalApps:%s@local-database-rw.database.svc.cluster.local/lldap" .password }}'
        LLDAP_JWT_SECRET: '{{ .jwt }}'
        LLDAP_KEY_SEED: '{{ .key }}'
        LLDAP_LDAP_USER_PASS: '{{ .adminPass }}'

  data:
  - secretKey: password
    remoteRef:
      key: "2414638d-a830-48e3-bcd1-b34500ed78c4"
  - secretKey: jwt
    remoteRef:
      key: "ce72e3d3-fbc1-43f9-920f-b354015c7003"
  - secretKey: key
    remoteRef:
      key: "bf26a811-c067-47c0-a213-b354015f149c"
  - secretKey: adminPass
    remoteRef:
      key: "e6002edb-0050-4328-9bf4-b354015cb99b"