controllers:
  blocky:
    type: deployment
    replicas: 3
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: 2
    containers:
      app:
        image:
          repository: ghcr.io/0xerr0r/blocky
          tag: v0.27.0
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
        resources:
          limits:
            cpu: 1
            memory: 420Mi
          requests:
            cpu: 50m
            memory: 250Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_BIND_SERVICE
            drop:
              - ALL
          readOnlyRootFilesystem: true
defaultPodOptions:
  securityContext:
    fsGroup: 568
    runAsGroup: 568
    runAsNonRoot: true
    runAsUser: 568
    seccompProfile:
      type: RuntimeDefault
  shareProcessNamespace: true
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - blocky
            topologyKey: kubernetes.io/hostname

service:
  app:
    controller: blocky
    labels:
      network: lan
    annotations:
      "lbipam.cilium.io/sharing-key": "blocky-shared"
      "lbipam.cilium.io/ips": "192.168.231.30"
    ports:
      dns-udp:
        port: 53
        protocol: UDP
      dns-tcp:
        port: 53
        protocol: TCP
    type: LoadBalancer
  
  metrics:
    controller: blocky
    type: ClusterIP
    ports:
      http:
        port: 4000
        primary: true