---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-lan-1
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-lan-1",
      "plugins": [
        {
          "type": "bridge",
          "master": "br0",
          "ipam": {
            "type": "static",
            "addresses": [
              {
                "address": "192.168.231.3/24",
                "gateway": "192.168.231.1"
              }
            ],
            "routes": [
              { "dst": "0.0.0.0/0" }
            ]
          }
        }
      ]
    }