---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: &clusterName galaxy-cluster

# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.10.6

# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.33.4

endpoint: https://192.168.31.31:6443
clusterPodNets:
  - "10.68.0.0/16"
clusterSvcNets:
  - "10.95.0.0/16"

additionalApiServerCertSans: &sans
  - k8s.de.plutode.com
  - &talosControlplaneVip 192.168.31.31
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: andromeda
    controlPlane: true
    ipAddress: 192.168.31.32
    installDisk: /dev/nvme1n1
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    talosImageURL: factory.talos.dev/metal-installer/c0e8a037ed69de7d8a380c5707524988e3eb387f4043880a168d911effb67a53
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/nvme-cli
    networkInterfaces:
      - interface: bond0
        addresses:
          - 192.168.31.32/24
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.31.1"
        vip:
          ip: *talosControlplaneVip
        bond:
          mode: 802.3ad
          lacpRate: fast
          xmitHashPolicy: layer3+4
          miimon: 100
          updelay: 200
          downdelay: 200
          interfaces:
            - eno1
            - enp2s0
        dhcp: false
        vlans:
          - vlanId: 10
            dhcp: false
            mtu: 1500
          - vlanId: 15
            dhcp: false
            mtu: 1500          
          - vlanId: 20
            dhcp: false
            mtu: 1500

  - hostname: milkyway
    controlPlane: true
    ipAddress: 192.168.31.33
    installDisk: /dev/nvme0n1
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
      hardware.plutode.com/display: "lcd"
      hardware.plutode.com/rgb: "true"
    talosImageURL: factory.talos.dev/metal-installer/c0e8a037ed69de7d8a380c5707524988e3eb387f4043880a168d911effb67a53
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/nvme-cli
    networkInterfaces:
      - interface: bond0
        addresses:
          - 192.168.31.33/24
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.31.1"
        vip:
          ip: *talosControlplaneVip
        bond:
          mode: 802.3ad
          lacpRate: fast
          xmitHashPolicy: layer3+4
          miimon: 100
          updelay: 200
          downdelay: 200
          interfaces:
            - enp4s0
            - enp2s0
        dhcp: false
        vlans:
          - vlanId: 10
            dhcp: false
            mtu: 1500
          - vlanId: 15
            dhcp: false
            mtu: 1500          
          - vlanId: 20
            dhcp: false
            mtu: 1500

  - hostname: triangulum
    controlPlane: true
    ipAddress: 192.168.31.34
    installDisk: /dev/vda
    talosImageURL: factory.talos.dev/metal-installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
    networkInterfaces:
      - interface: bond0
        addresses:
          - 192.168.31.34/24
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.31.1"
        vip:
          ip: *talosControlplaneVip
        bond:
          mode: 802.3ad
          lacpRate: fast
          xmitHashPolicy: layer3+4
          miimon: 100
          updelay: 200
          downdelay: 200
          interfaces:
            - ens7
        dhcp: false
        vlans:
          - vlanId: 10
            dhcp: false
            mtu: 1500
          - vlanId: 15
            dhcp: false
            mtu: 1500          
          - vlanId: 20
            dhcp: false
            mtu: 1500    

# Global patches
patches:
  - "@./patches/global/files.yaml"
  - "@./patches/global/kubelet.yaml"
  - "@./patches/global/network.yaml"
  - "@./patches/global/time.yaml"
  - "@./patches/global/sysctl.yaml"
  - "@./patches/global/openebs.yaml"

# Controller patches
controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *clusterName
    topology.kubernetes.io/zone: m
  patches:
    - "@./patches/controller/sysupgrade.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/disable-admission-controller.yaml"