apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      data:
        API_KEY: '{{ .api | toString }}'
  data:
  - secretKey: api
    remoteRef:
      key: "da8e27ff-a447-4517-96de-b26d01412596"
  - secretKey: DB_PASS
    remoteRef:
      key: "2414638d-a830-48e3-bcd1-b34500ed78c4"