apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: njalla-api-secret
spec:
  refreshInterval: 300s
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: token
    remoteRef:
      key: "3a62bcd3-de74-4430-9831-b3390151e3b8"