apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore

  # So that I can edit the resulting secret
  target:

    template:

      # Use inline templates to construct your desired config file that contains your secret
      data:
        DB_URL: '"{{ printf "postgresql://generalApps:%s@local-database-rw.database.svc.cluster.local/homeassistant" .password }}"'

  data:
  - secretKey: password
    remoteRef:
      key: "2414638d-a830-48e3-bcd1-b34500ed78c4"