---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-assistant
spec:
  interval: 1h
  url: http://pajikos.github.io/home-assistant-helm-chart/
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  timeout: 3m
  chart:
    spec:
      chart: home-assistant
      version: v0.3.17
      sourceRef:
        kind: HelmRepository
        name: home-assistant
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: home-assistant-values