---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: network/multus-local
          securityContext:
            runAsUser: 65534
            runAsGroup: 65533
            fsGroup: 65533
            fsGroupChangePolicy: OnRootMismatch

        initContainers:
          setup-config:
            enabled: true
            env:
              FORCE_INIT: false
            image:
              repository: mikefarah/yq
              tag: "4"
              pullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args:
              - /bin/sh /mnt/init/init.sh

          init-hacs:
            enabled: true
            image:
              repository: bash
              tag: "latest"
            command: ["bash", "-c", "cd /config && wget -O - https://get.hacs.xyz | bash -"]

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.8.3@sha256:7ef14f513e487add292b43306cccb4f1cd9dbcbd5eaf85d6438f98b197f930a4 
            envFrom:
              - secretRef:
                  name: home-assistant-secrets
            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        primary: true
        controller: home-assistant
        type: ClusterIP
        ports:
          http:
            port: 8123

    persistence:
      config:
        name: hass-config
        type: configMap
        advancedMounts:
          home-assistant:
            setup-config:
              - path: /config-templates

      config-claim:
        existingClaim: hass-config
        advancedMounts:
          home-assistant:
            app:
              - path: /config
            setup-config:
              - path: /config
            init-hacs:
              - path: /config

      init-script:
        type: configMap
        name: init-script
        defaultMode: 511
        advancedMounts:
          home-assistant:
            setup-config:
              - path: /mnt/init
            
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: hass-tmp

    ingress:
      app:
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: "temp.ha.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: home-assistant-tls
            hosts:
              - temp.ha.${SECRET_DOMAIN}