apiVersion: v1
data:
  values.yaml: "# Default values for home-assistant.\n# This is a YAML-formatted file.\n#
    Declare variables to be passed into your templates.\n\n# Number of replicas for
    the deployment\nreplicaCount: 1\n\n# Image settings\nimage:\n  # Repository for
    the Home Assistant image\n  repository: ghcr.io/home-assistant/home-assistant\n
    \ # Image pull policy\n  pullPolicy: IfNotPresent\n\npersistence:\n  enabled:
    true\n  storageClass: \"openebs-hostpath\"\n  accessMode: ReadWriteOnce\n  size:
    5Gi\n\npodSecurityContext:\n  runAsUser: 1000\n  runAsGroup: 1000\n  fsGroup:
    1000\n  fsGroupChangePolicy: \"OnRootMismatch\"\n\nsecurityContext:\n  capabilities:\n
    \   drop:\n    - ALL\n  readOnlyRootFilesystem: true\n  runAsNonRoot: true\n  runAsUser:
    1000\n\npodAnnotations:\n  k8s.v1.cni.cncf.io/networks: network/multus-local\n\nstatefulSetAnnotations:\n
    \ reloader.stakater.com/auto: \"true\"\n\n# Ingress settings\ningress:\n  # Enable
    ingress for home assistant\n  enabled: true\n  annotations:\n    kubernetes.io/tls-acme:
    \"true\"\n    cert-manager.io/cluster-issuer: letsencrypt-prod\n  hosts:\n    -
    host: \"ha.${SECRET_DOMAIN}\"\n      paths:\n        - path: /\n          pathType:
    Prefix\n  tls:\n    - secretName: home-assistant-tls\n      hosts:\n        -
    \"ha.${SECRET_DOMAIN}\"\n\n# Configuration for Home Assistant\nconfiguration:\n
    \ # Enable or disable the configuration setup for Home Assistant\n  enabled: true\n\n
    \ templateConfig: |-\n    # Loads default set of integrations. Do not remove.\n
    \   default_config:\n\n    {{- if or .Values.ingress.enabled .Values.ingress.external
    }}\n    http:\n      use_x_forwarded_for: true\n      trusted_proxies:\n        {{-
    range .Values.configuration.trusted_proxies }}\n        - {{ . }}\n        {{-
    end }}\n    {{- end}}\n    # Load frontend themes from the themes folder\n    frontend:\n
    \     themes: !include_dir_merge_named themes\n\n    recorder:\n      db_url:
    !env_var DB_URL\n      db_retry_wait: 15 # Wait 15 seconds before retrying\n      exclude:\n
    \       domains:\n          - updater\n        entity_globs:\n          - sensor.weather_*\n
    \       entities:\n          - sun.sun # Don't record sun data\n          - sensor.last_boot
    # Comes from 'systemmonitor' sensor platform\n          - sensor.date\n        event_types:\n
    \         - call_service # Don't record service cal\n\n    automation: !include
    automations.yaml\n    script: !include scripts.yaml\n    scene: !include scenes.yaml\n\nenv:
    \n  - name: TZ\n    value: \"${SECRET_TZ}\"\n\nenvFrom: \n  - secretRef:\n    name:
    home-assistant-secrets\n\n\nserviceMonitor:\n  # requires HA integration:  https://www.home-assistant.io/integrations/prometheus/\n
    \ enabled: false\n  scrapeInterval: 30s\n\n# Addons configuration for additional
    services\naddons:\n  # Code-server addon configuration\n  codeserver:\n    # Enable
    or disable the code-server addon\n    enabled: true\n    ingress:\n      # Enable
    or disable the ingress for the code-server addon\n      enabled: true\n      #
    Ingress annotations\n      annotations:\n        kubernetes.io/tls-acme: \"true\"\n
    \       cert-manager.io/cluster-issuer: letsencrypt-prod\n      # Ingress hosts
    configuration\n      hosts:\n        - host: \"edit.ha.${SECRET_DOMAIN}\"\n          paths:\n
    \           - path: /\n              pathType: Prefix\n      # Ingress TLS configuration\n
    \     tls:\n        - secretName: code-server-ha-tls\n          hosts:\n            -
    \"edit.ha.${SECRET_DOMAIN}\"\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: home-assistant
    kustomize.toolkit.fluxcd.io/name: home-assistant
    kustomize.toolkit.fluxcd.io/namespace: default
  name: home-assistant-values-g6b545htfk
  namespace: default
