---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: redis
  namespace: redis
spec:
  interval: 1h
  url: https://ot-container-kit.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-operator
      version: 0.22.1
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: redis
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    redisOperator:
      webhook: true
    
    issuer:
    # Whether to create the issuer or not. You might want to disable this if instead you
    # want to use a ClusterIssuer that you simply want to provide.
      create: true
      kind: Issuer
      type: selfSigned
      name: redis-operator-issuer

    service:
      name: webhook-service
      namespace: redis  

    certmanager:
      # Whether to use cert-manager for certificate management
      # Only effective when webhook=true
      # If webhook=true and certmanager.enabled=false, you need to manually create certificate secret
      enabled: true
      # API version of the cert-manager CRDs
      apiVersion: "cert-manager.io/v1"

    podSecurityContext: 
      fsGroup: 1000

    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000