apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: split-pro-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      data:
        DATABASE_URL: '{{ printf "postgresql://generalApps:%s@local-database-rw.database.svc.cluster.local/split-pro" .password }}'
        NEXTAUTH_SECRET: '{{ .nextauth | toString }}'
        OIDC_CLIENT_SECRET: '{{ .oidc | toString }}'
  data:
  - secretKey: nextauth
    remoteRef:
      key: "3ffd676b-3c5a-4468-ab49-b35a01792921"
  - secretKey: oidc
    remoteRef:
      key: "f6ed16d8-1c61-44c1-a3ff-b35a0178de7b"
  - secretKey: password
    remoteRef:
      key: "2414638d-a830-48e3-bcd1-b34500ed78c4"