apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      data:
        PROWLARR__AUTH__APIKEY: '{{ .api | toString }}'
        ROWLARR__POSTGRES__PASSWORD: '{{ .password | toString }}'
  data:
  - secretKey: api
    remoteRef:
      key: "31c25d45-71a9-4e59-8470-b26d00edbd73"
  - secretKey: password
    remoteRef:
      key: "2414638d-a830-48e3-bcd1-b34500ed78c4"