---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: invidious
spec:
  interval: 1h
  url: https://ildoc.github.io/invidious-helm-chart/
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invidious
spec:
  interval: 30m
  timeout: 3m
  chart:
    spec:
      chart: invidious
      version: v3.0.0
      sourceRef:
        kind: HelmRepository
        name: invidious
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: invidious-values
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              name: invidious
            patch: |
              - op: replace
                path: /spec/ports/0/targetPort
                value: 3000