# Setting replicaCount higher than 1 may cause PostgreSQL database deadlocks.
# This happens when multiple Invidious processes simultaneously attempt to refresh channel subscriptions for users.
replicaCount: 1

image:
  tag: "2.20250913.0"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: inv.${SECRET_DOMAIN}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: invidious-tls
      hosts:
        - inv.${SECRET_DOMAIN}

# Reference: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
postgresql:
  enabled: false

# Reference: https://github.com/iv-org/invidious/blob/master/config/config.example.yml
config:
  db:
    user: generalApps
    host: local-database-rw.database.svc.cluster.local
    port: 5432
    dbname: invidious
  port: 3000
  check_tables: true
  external_port: 443
  domain: "inv.${SECRET_DOMAIN}"
  https_only: true
  channel_threads: 1
  full_refresh: false
  feed_threads: 1
  captcha_enabled: false
  admins: ["Collin"]
  local: true

# -- Secret management configuration
# Use existingSecret to reference an existing Kubernetes secret for production deployments
existingSecret: "invidious-secrets"

# -- Invidious Companion configuration (replaces sighelper for YouTube interaction)
companion:
  # -- Enable Invidious Companion deployment
  enabled: true
  # -- Companion container image configuration
  image:
    # -- Companion container image repository
    repository: quay.io/invidious/invidious-companion
    # -- Companion container image tag (aligned with docker-compose template)
    tag: "master-a866b71"

  # -- Companion resource limits and requests
  resources:
    # -- Resource limits for companion
    limits:
      # -- CPU limit for companion
      cpu: 200m
      # -- Memory limit for companion
      memory: 1024Mi
    # -- Resource requests for companion
    requests:
      # -- CPU request for companion
      cpu: 100m
      # -- Memory request for companion
      memory: 512Mi
  

  # -- Persistent volume configuration for companion cache
  persistence:
    # -- Enable persistent volume for YouTube library cache
    enabled: true
    # -- Size of the persistent volume
    size: 1Gi
    # -- Access mode for the persistent volume
    accessMode: ReadWriteOnce
    # -- Storage class name (leave empty to use default)
    storageClass: "openebs-hostpath"