---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./blocky/ks.yaml
  - ./multus/ks.yaml
  - ./whereabouts/ks.yaml
  - ./tailscale-sr/ks.yaml
  - ./mosquitto/ks.yaml
