---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitwarden
  namespace: bitwarden-secrets # Required for Renovate lookups
spec:
  interval: 1h
  url: https://charts.bitwarden.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: sm-operator
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: bitwarden
        namespace: bitwarden-secrets
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: bitwarden-secrets-helm-values
    
